# Generated by Django 6.1.1 on 2026-10-02 12:36

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='ad')),
                ('slug', models.SlugField(max_length=60, unique=True, verbose_name='slug')),
                ('description', models.CharField(blank=True, max_length=160, verbose_name='açıklama')),
                ('icon', models.CharField(blank=True, help_text="Frontend'deki ikon adı (ör. code, brain).", max_length=40, verbose_name='ikon')),
                ('color', models.CharField(max_length=7, validators=[django.core.validators.RegexValidator(message='Renk #RRGGBB biçiminde olmalı (ör. #3B82F6).', regex='^#[0-9A-Fa-f]{6}$')], verbose_name='renk')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='sıra')),
                ('is_active', models.BooleanField(default=True, verbose_name='aktif')),
            ],
            options={
                'verbose_name': 'kategori',
                'verbose_name_plural': 'kategoriler',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=120, verbose_name='soru')),
                ('difficulty', models.PositiveSmallIntegerField(choices=[(1, 'Kolay'), (2, 'Orta'), (3, 'Zor')], default=1, verbose_name='zorluk')),
                ('explanation', models.TextField(blank=True, verbose_name='açıklama')),
                ('is_active', models.BooleanField(default=True, verbose_name='aktif')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='oluşturulma')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='güncellenme')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='questions', to='quiz.category', verbose_name='kategori')),
            ],
            options={
                'verbose_name': 'soru',
                'verbose_name_plural': 'sorular',
                'ordering': ['category', 'difficulty', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=40, verbose_name='şık')),
                ('is_correct', models.BooleanField(default=False, verbose_name='doğru')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='sıra')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='quiz.question', verbose_name='soru')),
            ],
            options={
                'verbose_name': 'şık',
                'verbose_name_plural': 'şıklar',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='QuizSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token_hash', models.CharField(editable=False, max_length=64, unique=True, verbose_name='token hash')),
                ('status', models.CharField(choices=[('in_progress', 'Devam ediyor'), ('completed', 'Tamamlandı'), ('expired', 'Süresi doldu')], default='in_progress', max_length=16, verbose_name='durum')),
                ('current_index', models.PositiveSmallIntegerField(default=0, help_text='0–20; cevaplanan/süresi dolan soru sayısı.', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)], verbose_name='cevaplanan soru sayısı')),
                ('score', models.PositiveIntegerField(default=0, verbose_name='puan')),
                ('correct_count', models.PositiveSmallIntegerField(default=0, verbose_name='doğru sayısı')),
                ('total_time_ms', models.PositiveIntegerField(default=0, verbose_name='toplam süre (ms)')),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='başlangıç')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='bitiş')),
                ('client_type', models.CharField(choices=[('web', 'Web'), ('ios', 'iOS'), ('android', 'Android')], default='web', max_length=8, verbose_name='istemci')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sessions', to='quiz.category', verbose_name='kategori')),
            ],
            options={
                'verbose_name': 'quiz oturumu',
                'verbose_name_plural': 'quiz oturumları',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='SessionQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)], verbose_name='sıra')),
                ('choice_order', models.JSONField(default=list, help_text='İstemciye gösterilen şık ID sırası.', verbose_name='şık sırası')),
                ('served_at', models.DateTimeField(blank=True, help_text='Sayacın başladığı sunucu zamanı (geri bildirim/3-2-1 kadar ileri tarihli).', null=True, verbose_name='gösterilme')),
                ('answered_at', models.DateTimeField(blank=True, null=True, verbose_name='cevaplanma')),
                ('is_correct', models.BooleanField(blank=True, null=True, verbose_name='doğru mu')),
                ('timed_out', models.BooleanField(default=False, verbose_name='süre doldu')),
                ('response_ms', models.PositiveIntegerField(blank=True, null=True, verbose_name='cevap süresi (ms)')),
                ('points', models.PositiveSmallIntegerField(default=0, verbose_name='puan')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='quiz.question', verbose_name='soru')),
                ('selected_choice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='quiz.choice', verbose_name='seçilen şık')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_questions', to='quiz.quizsession', verbose_name='oturum')),
            ],
            options={
                'verbose_name': 'oturum sorusu',
                'verbose_name_plural': 'oturum soruları',
                'ordering': ['session', 'order'],
            },
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['category', 'is_active', 'difficulty'], name='question_pick_idx'),
        ),
        migrations.AddConstraint(
            model_name='question',
            constraint=models.CheckConstraint(condition=models.Q(('difficulty__gte', 1), ('difficulty__lte', 3)), name='question_difficulty_range'),
        ),
        migrations.AddConstraint(
            model_name='choice',
            constraint=models.UniqueConstraint(condition=models.Q(('is_correct', True)), fields=('question',), name='choice_single_correct_per_question'),
        ),
        migrations.AddIndex(
            model_name='quizsession',
            index=models.Index(fields=['status', 'started_at'], name='session_status_started_idx'),
        ),
        migrations.AddConstraint(
            model_name='quizsession',
            constraint=models.CheckConstraint(condition=models.Q(('current_index__lte', 20)), name='session_current_index_max_20'),
        ),
        migrations.AddConstraint(
            model_name='sessionquestion',
            constraint=models.UniqueConstraint(fields=('session', 'order'), name='session_question_order'),
        ),
        migrations.AddConstraint(
            model_name='sessionquestion',
            constraint=models.UniqueConstraint(fields=('session', 'question'), name='session_question_once'),
        ),
        migrations.AddConstraint(
            model_name='sessionquestion',
            constraint=models.CheckConstraint(condition=models.Q(('order__gte', 1), ('order__lte', 20)), name='session_question_order_range'),
        ),
    ]
