# Generated by Django 6.1.1 on 2026-10-02 12:36

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaderboardEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_name', models.CharField(max_length=20, validators=[django.core.validators.MinLengthValidator(2)], verbose_name='oyuncu adı')),
                ('score', models.PositiveIntegerField(verbose_name='puan')),
                ('correct_count', models.PositiveSmallIntegerField(verbose_name='doğru sayısı')),
                ('total_time_ms', models.PositiveIntegerField(verbose_name='toplam süre (ms)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='kayıt zamanı')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='leaderboard_entries', to='quiz.category', verbose_name='kategori')),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='leaderboard_entry', to='quiz.quizsession', verbose_name='oturum')),
            ],
            options={
                'verbose_name': 'skor',
                'verbose_name_plural': 'skorlar',
                'ordering': ['-score', 'total_time_ms', 'created_at'],
                'indexes': [models.Index(fields=['category', '-score', 'total_time_ms', 'created_at'], name='leaderboard_rank_idx')],
            },
        ),
    ]
